version: '3.8'
services:
  weaviate-gdc:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
    ports:
      - "8100:8100"